# coding:utf-8
"""回复卡片窗口动画和堆叠常量。"""

from PySide6.QtCore import QPoint

CARD_STACK_GAP = 10
CARD_BASE_GAP = 18
CARD_ENTER_OFFSET = QPoint(0, -14)
CARD_EXIT_OFFSET = QPoint(0, -10)
CARD_ANIM_IN_MS = 220
CARD_ANIM_MOVE_MS = 180
CARD_ANIM_OUT_MS = 180
MAX_STACKED_REPLY_CARDS = 4
REPLY_CARD_TIMEOUT_MS = 12000
